### ISSUE TITLE
Keyboard text backwards

### ISSUE THREAD

**Issue by davesayers2014** [oe-mirrors/e2iplayer#8]
Using e2iplayer search when using the keyboard it seems to type the text backwards when searching

**Comment by Masta2002** [comment]
@davesayers2014 is this issue still present or can it close?

**Comment by davesayers2014** [comment]
I haven't used e2iplayer for a while but when trying to test it today I received a crash

`Traceback (most recent call last):
< 55975.368732> 22:54:34.9004   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 58, in action
< 55975.369169> 22:54:34.9008   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 148, in keySelect
< 55975.369467> 22:54:34.9011   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 152, in run
< 55975.369739> 22:54:34.9014   File "/usr/lib/enigma2/python/Plugins/Plugin.py", line 110, in __call__
< 55975.370030> 22:54:34.9017   File "/home/ubuntu/6.7.1/builds/openvix/developer/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-e2iplayer/enigma2-plugin-extensions-e2iplayer-git-r0/image/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/plugin.py", line 94, in main
< 55975.370309> 22:54:34.9020   File "/home/ubuntu/6.7.1/builds/openvix/developer/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-e2iplayer/enigma2-plugin-extensions-e2iplayer-git-r0/image/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/plugin.py", line 122, in runMain
< 55975.370579> 22:54:34.9022   File "/home/ubuntu/6.7.1/builds/openvix/developer/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-e2iplayer/enigma2-plugin-extensions-e2iplayer-git-r0/image/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/plugin.py", line 118, in doRunMain
< 55975.370847> 22:54:34.9025   File "/usr/lib/enigma2/python/StartEnigma.py", line 161, in open
< 55975.371550> 22:54:34.9032     self.execBegin()
< 55975.371759> 22:54:34.9034   File "/usr/lib/enigma2/python/StartEnigma.py", line 87, in execBegin
< 55975.372220> 22:54:34.9039     currentDialog.show()
< 55975.372371> 22:54:34.9040   File "/usr/lib/enigma2/python/Screens/Screen.py", line 145, in show
< 55975.372700> 22:54:34.9043   File "/home/ubuntu/6.7.1/builds/openvix/developer/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-e2iplayer/enigma2-plugin-extensions-e2iplayer-git-r0/image/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvplayerwidget.py", line 1109, in onStart
< 55975.373074> 22:54:34.9047   File "/home/ubuntu/6.7.1/builds/openvix/developer/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-e2iplayer/enigma2-plugin-extensions-e2iplayer-git-r0/image/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvplayerwidget.py", line 1126, in selectHost
< 55975.373370> 22:54:34.9050   File "/home/ubuntu/6.7.1/builds/openvix/developer/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-e2iplayer/enigma2-plugin-extensions-e2iplayer-git-r0/image/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/iptvplayerwidget.py", line 1140, in selectGroup
< 55975.373637> 22:54:34.9053   File "/usr/lib/enigma2/python/StartEnigma.py", line 150, in openWithCallback
< 55975.374112> 22:54:34.9058     dialog = self.open(screen, *arguments, **kwargs)
< 55975.374509> 22:54:34.9062              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
< 55975.374555> 22:54:34.9062   File "/usr/lib/enigma2/python/StartEnigma.py", line 158, in open
< 55975.374974> 22:54:34.9066     dialog = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
< 55975.375502> 22:54:34.9071                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
< 55975.375577> 22:54:34.9072   File "/usr/lib/enigma2/python/StartEnigma.py", line 100, in instantiateDialog
< 55975.376059> 22:54:34.9077     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
< 55975.376538> 22:54:34.9082            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
< 55975.376584> 22:54:34.9082   File "/usr/lib/enigma2/python/StartEnigma.py", line 127, in doInstantiateDialog
< 55975.376978> 22:54:34.9086     dialog.applySkin()
< 55975.377180> 22:54:34.9088   File "/usr/lib/enigma2/python/Screens/Screen.py", line 272, in applySkin
< 55975.377509> 22:54:34.9092   File "/usr/lib/enigma2/python/Screens/Screen.py", line 304, in createGUIScreen
< 55975.377787> 22:54:34.9094   File "/home/ubuntu/6.7.1/builds/openvix/developer/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-e2iplayer/enigma2-plugin-extensions-e2iplayer-git-r0/image/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/playerselector.py", line 178, in layoutFinished
< 55975.378082> 22:54:34.9097   File "/home/ubuntu/6.7.1/builds/openvix/developer/vuuno4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-e2iplayer/enigma2-plugin-extensions-e2iplayer-git-r0/image/usr/lib/enigma2/python/Plugins/Extensions/IPTVPlayer/components/playerselector.py", line 220, in setSelectionImage
< 55975.378479> 22:54:34.9101 AttributeError: 'NoneType' object has no attribute 'master'
< 55975.378553> 22:54:34.9102 [ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.HelpableActionMap object at 0xac628498>>,('OkCancelActions', 'ok')) failed)`

**Comment by davesayers2014** [comment]
Vix 7.7.015 release image /

I have installed e2iplayer after not using it for a while and this installs ok

Re search issue with backwards text seems ok although the issue seemed to have been with e2iplayer keyboard. On Vix 7.7.015  e2iplayer seems to use the image virtual keyboard this was different when I reported the error. If the keyboard has changed this issue can be closed.

![Image](https://github.com/user-attachments/assets/94320cf8-e1e3-4900-a1c4-0bd117e56cfc)

Edit after checking e2iplayer, Configuration Virtual keyboard type: own model 

The search is backwards. Using search typing home shows no text

Choosing search history the text is backwards 

![Image](https://github.com/user-attachments/assets/b7621845-2cc5-4599-9d97-a57692623f21)

Going back into search the keyboard text is backwards 

![Image](https://github.com/user-attachments/assets/e2197d71-d22b-430e-be6b-9dba4513ed4a)

**Comment by Masta2002** [comment]
i cant reproduce this error on oATV 7.6
